### ISSUE TITLE
demo checklist

### ISSUE THREAD

**Issue by raprasad** [opendifferentialprivacy/opendp-ux#296]
- [x] Validate statistics: UI end-to-end test
- [x] Cypress testing #326 - full demo test
- [x] Release statistics
  - [x] ~~async hookup / websockets~~; code allows hookup but fast enough for demo now
  - [x] Release statistics: tests 
  - [x] DP Release page #324 - See Issue for example of JSON to format
     - [x] @raprasad further formatting to fill in Release JSON info dynamically #299 
  - [x] Generate PDF report #33
- Additional statistics
  - [x] DP Count #311
- Dataverse deposit @raprasad 
   - [x] Deposit JSON, PDF #34
- Demo: test dataset - PUMS data #308 (from @tercer)
  - [x] Demo: create Dataverse dataset + file (repeatable process/API?)
  - [x] Demo: end to end test
- [x] update AnalysisPlan.variable_info if DepositorSetupInfo updated @raprasad 
---

### lower priority / non-essential
- [x] Accuracy not showing on stats table: #336
- [x] Lock AnalysisPlan UI updates #297
- [x] Profiler: adjust to choose int/float instead of simply "numeric" based on existing data that is "purged"
- [ ] UI: remove ^/down arrows for epsilon, delta, min/max edits; e.g. must be typed in
- [x] #466
- [x] non-breaking bug re: user storage #330
- [x] https://github.com/opendp/dpcreator/issues/300
- [x] DP Histogram @ecowan #320
    -  @ecowan send example output (list of tuples, etc)
#### deploy
- [x] add google settings to azure (need SSL to be done)
- [x] add email settings to azure
- [x] double-check clear data endpoint is in a different settings file; yes only in cypress_setting that adds separate app
- [ ] azure blob storage

**Comment by raprasad** [comment]
closing, items complete or moved to other issues
