### ISSUE TITLE
Tutorial Notes from 2/15/2022

### ISSUE THREAD

**Issue by raprasad** [opendifferentialprivacy/opendp-ux#515]
Items to prioritize...

(Note: A ~~crossed out item~~ indicates that the item is now a separate issue--not that it is necessarily complete

### Tutorial Notes from 2/15/2022
Reference document: https://docs.google.com/document/d/1cjogg37M069Y5JwOJ5FC6w_BAqhyUmgag6eXXpJmegA/edit

- [x] 1. For the tutorial test files, include codebooks, information about the files
- [x] 2. ~~Publish a list of statistics available through DP Creator~~ #543
	- Live on GitHub page in dpcreator app
- [x] 3. Mike’s text edits on page 4
	- Check with Salil about “carefully calibrated ….” 
	- **^ Check with Salil, put text in a google doc format to edit**
- [x] 4. Add examples of "What can be done with the DP Release?" moved to #601 
	- Show example releases on the web page!
	- Expand tip/link tip to a separate page?
- [x] 5. ~~Within Wizard pages, move the "continue" button to the bottom of the page~~ #527 
	- ~~Add “Go Back” to bottom of each page~~
- [x] 6. Page 6, Number 5, text changes per Salil
- [x] ~~7. Page 6, Number 5, 2nd question refers to the “University”~~ (captured on user review sheet)
	- Adjust for general use
- [x] 8. ~~Add row transform functionality (create new variables as formulas/functions of the existing ones? (“row transforms”?))~~ #541
- [x] 9. Instructions for the confirm variables page (notes)
	- *Rewrite for the Curator! (Who has access to the data)*
		- Re-examine with Salil!
- [x] 10. ~~Confirm variables, category entry.~~ covered in #504 #508
	- Add to instructions “use Return/Enter to add a category”
	- Estimate the categories (use Return/Enter to add a category) for the Categorical variables, and min and max for the Integer or Float variables.  For Boolean type, you don’t need to add any value.
- [x] 11. Set Accuracy Level page (captured on user review sheet)
	- Need new title, ask Salil/Mike/Andy/etc.
- [x] 12. User has to have basic DP familiarity!  (Ongoing educational issue! Being discussed outside of this ticket)
	- What does this mean? How much do you need to know to use the app?
	- Where’s your DP certificate?
- [x] ~~12.5 - Significant Digits for Epsilon; Error/Accuracy level.~~ #516 
	- Round the level of error (Ethan/Mike/Andy?)
	- Display layer in .js, change the precision to 2-3? digits. How many significant digits are useful?
	- Splitting epsilon: change the precision to 2-3? digits. 
		- .01 to 1
- [x] ~~13. “Statistics are being processed” title of pop-up~~ #520
	- ~~title and text should change if the Release completes while the box is still visible~~
- [x] ~~14. Activate send email functionality~~ #535
	- Submission email confirmation
	- Release ready email
	- Is the confirmation email being sent that the Release is ready!!!
- [x] ~~15 .Lock functionality.~~ #565
	- move lock next to epsilon
	- “pinning” the value; (chain/unchain icon; photoshop)
	- icon should show current state
		- If unlocked: allow editing of epsilon
		- if locked: no editing
	- need to show user how this works
- [x] ~~16. Generate DP Release page~~  #536
	- Where is my shopping cart?
	- Show what the person is “ordering” in their release…
		- List the statistics to compute
	- What will happen after I submit?
		- deposit to DV, etc.
- [x]  ~~17. histogram formatting.~~ #506
	- simple table?
- [x] 18. Create statistic page, examine language on “splitting the budget” (captured on user review sheet)

**Comment by anniewu332** [comment]
I'm thinking of the version for Harvard Dataverse curators to test as the demo release.  My suggestion for demo-priority: 2, 3, 6, 7, 9, 10, 11, the one between 12 and 13 on number of digits, 14 (if too big a lift then change the text instead of sending email).  Several of these are text edits we need the input and review from Salil and others on the team - let's try to get that done next week, if possible.

**Comment by raprasad** [comment]
Closing. Items moved to other issues or completed
