### ISSUE TITLE
PDF tweaks/updates

### ISSUE THREAD

**Issue by raprasad** [opendifferentialprivacy/opendp-ux#554]
- [x] Link section headers to appropriate pages. moved to #576
- [x] Add more text
- [x] Histograms: - moved to #649
   - [x] When too many categories for a chart, show a smaller table, with first _n_ rows
   - [ ] For any negative values, link to the _n_th page which explains negative values
- [x] Add section with code snippets of how to access the data via JSON - moved to #650
   - Perhaps per stat? especially histogram with too many categories
- [x] For dynamic tables, perhaps add some formatting info to the JSON release. Or equivalent param structure, etc.
- [x] Add answers to epsilon questions (see SetupQuestionFormatter which adds ?s to the release json)

**Comment by raprasad** [comment]
remaining items moved to separate issues
